# Generated by Django 5.2 on 2025-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_organiser_options_alter_organiser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='organiser_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='organiser_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='organiser_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
