# Generated by Django 5.2 on 2025-05-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='organiser',
            name='primary_color',
            field=models.CharField(default='#4285f4', max_length=7),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
